# Generated by Django 3.2.7 on 2021-10-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblCatalog',
            fields=[
                ('pd_sl', models.FloatField(blank=True, db_column='PD_SL', null=True)),
                ('po_no', models.CharField(blank=True, db_column='PO_NO', max_length=255, null=True)),
                ('gender', models.CharField(blank=True, db_column='GENDER', max_length=255, null=True)),
                ('category', models.CharField(blank=True, db_column='CATEGORY', max_length=255, null=True)),
                ('last', models.CharField(blank=True, db_column='LAST', max_length=255, null=True)),
                ('art_no', models.CharField(blank=True, db_column='ART_NO', max_length=255, null=True)),
                ('leather_1', models.CharField(blank=True, db_column='LEATHER_1', max_length=255, null=True)),
                ('leather_2', models.CharField(blank=True, db_column='LEATHER_2', max_length=255, null=True)),
                ('lining_1', models.CharField(blank=True, db_column='LINING_1', max_length=255, null=True)),
                ('lining_2', models.CharField(blank=True, db_column='LINING_2', max_length=255, null=True)),
                ('socks_design', models.CharField(blank=True, db_column='SOCKS_DESIGN', max_length=255, null=True)),
                ('sole', models.CharField(blank=True, db_column='SOLE', max_length=255, null=True)),
                ('size', models.FloatField(blank=True, db_column='SIZE', null=True)),
                ('sl', models.AutoField(db_column='SL', primary_key=True, serialize=False)),
                ('new_coll', models.IntegerField(blank=True, db_column='NEW_COLL', null=True)),
            ],
            options={
                'db_table': 'tbl_catalog',
                'managed': False,
            },
        ),
    ]
